name = "smartindie-click-tracker"
main = "worker/click-tracker.js"
compatibility_date = "2026-02-18"
workers_dev = false

routes = [
  { pattern = "go.smartindie.dev", custom_domain = true }
]

analytics_engine_datasets = [
  { binding = "CLICKS", dataset = "CLICKS" }
]

[vars]
SKOOL_TARGET = "https://www.skool.com/smart-indie-6927/about?ref=6e183e0cb40b468289dc9bf659028fe2"
